skip-changelog:
  - any: [ '.gitattributes', '.github/**/*', '.gitignore', 'crowdin.yml', '.mvn/**/*' ]

dependencies:
  - any: [ 'pom.xml' ]

documentation:
  - any: [ '*.adoc', '*.md', '*.txt', '**/*.html', '**/*.png', 'LICENSE*' ]

tests:
  - any: [ 'src/test/**/*' ]
